<?xml version="1.0"?>
    <package format="3">
    <name>robot_description</name>
    <version>0.1.0</version>
    <description>Magnetic spherical tank climbing simulation: robot_description</description>
    <maintainer email="maintainer@example.com">Climb Robot Maintainers</maintainer>
    <license>Apache-2.0</license>
    <buildtool_depend>ament_cmake</buildtool_depend>
    <depend>xacro</depend>
    <depend>third_party</depend>
    <exec_depend>gazebo_plugins</exec_depend>
    <exec_depend>robot_control_driver</exec_depend>
    <exec_depend>ur_description</exec_depend><exec_depend>gazebo_ros2_control</exec_depend><exec_depend>joint_state_broadcaster</exec_depend><exec_depend>joint_trajectory_controller</exec_depend><export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
